Homework-12
Otus-DevOps-2017-11/rastamalik_infra pull request #10
Opened 2018-01-26 13:22 UTC by rastamalik

Выполнено ДЗ-13

2018-01-26 13:30 UTC, Nklya requested changes
И зачем ты смержил испорченный бранч в мастер? 
Теперь весь этот мусор в мастере.

Папки terraform и ansible нужно привести в порядок и вычистить то, чего там не должно быть.

Пример того, что должно быть, приведены в слайдах.

Либо например 
https://github.com/Otus-DevOps-2017-11/Raian13_infra/tree/ansible-3/ansible
https://github.com/Otus-DevOps-2017-11/Raian13_infra/tree/ansible-3/terraform

2018-01-26 13:41 UTC, Nklya commented
А еще лучше откати мастер до состояния когда его еще не испортил.

2018-01-26 13:42 UTC, rastamalik commented
А как, где почитать?

2018-01-26 16:41 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> А еще лучше откати мастер до состояния когда его еще не испортил.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/10#issuecomment-360787464>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsDrv7LkRbCwxvC_FaPNWdxZRDygPks5tOdYTgaJpZM4RuSt2>
> .
>

2018-01-26 13:58 UTC, Nklya commented
Например https://githowto.com/ru

2018-01-26 14:15 UTC, closed without merging

2018-01-30 13:17 UTC, rastamalik commented
Поправил.

2018-01-26 16:58 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> Например https://githowto.com/ru
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/10#issuecomment-360791261>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsO-wDMDk7jtgb13wv8W_reFKdNbEks5tOdnqgaJpZM4RuSt2>
> .
>