Homework-13
Otus-DevOps-2017-11/rastamalik_infra pull request #12
Opened 2018-01-29 08:45 UTC by rastamalik

Выполнено ДЗ-13

2018-01-30 13:45 UTC, Nklya requested changes
Ревью после фикса предыдущего PR

2018-01-31 09:28 UTC, rastamalik commented
Поправил, откатил ненужные коммиты, обновил ветку.

2018-01-30 16:45 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> *@Nklya* requested changes on this pull request.
>
> Ревью после фикса предыдущего PR
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/12#pullrequestreview-92562165>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsArpnwVfprppAhtx2bcUNKv6Ea09ks5tPxzpgaJpZM4RwPYR>
> .
>

2018-01-31 10:37 UTC, Nklya requested changes
Нужно:
1. Вычистить дичь с шаблонами пакера в плейбуках
2. Вычистить vars из плейбуков
3. Добавить vars от nginx обратно в роль app

P.S. И следующие ДЗ сдавай пожалуйста по схеме:
* Создаешь ветку от мастера.
* Выполняешь задания
* Делаешь PR и ждешь проверки его.
* Когда проверен, мержишь в мастер и продолжаешь с пункта 1 следующее ДЗ, если у тебя проблемы с Git.

2018-01-31 10:37 UTC, Nklya commented on ansible/playbooks/app.json
> +{
Это здесь зачем?
Ансибл нужно было добавить в те шаблоны пакера, которые уже были.
Это надо вычистить.

2018-01-31 10:37 UTC, Nklya commented on ansible/playbooks/app.yml
> +      nginx_sites:
Переменных в плейбуках быть не должно.
В слайдах же написано, куда мы их заносим.
Это надо вычистить.

2018-01-31 10:37 UTC, Nklya commented on ansible/playbooks/db.json
> +{
Это здесь зачем?
Ансибл нужно было добавить в те шаблоны пакера, которые уже были.
Это надо вычистить.

2018-01-31 10:37 UTC, Nklya commented on ansible/playbooks/variables.json.example
> +{
Это здесь зачем?
Ансибл нужно было добавить в те шаблоны пакера, которые уже были.
Это надо вычистить.

2018-01-31 10:53 UTC, Nklya reviewed
У тебя весьма объемное README по этой ДЗ, которое не очень стыкуется с выполненными задачами

2018-01-31 10:53 UTC, Nklya commented on README.md
> +      nginx_sites:
Если мы переменные уже передаем в ansible в вагрантфайле, то зачем переменные nginx засовывать в плейбук?

2018-01-31 10:53 UTC, Nklya commented on README.md
> +Создал репозиторий **test-ansible-role-with-travis** из вынесенной роли **db**, подключил **TravisCL** для прогона тестов в GCE,
А как можно из этого описание понять где находится репозиторий?

2018-01-31 10:53 UTC, Nklya commented on README.md
> +32. Используем роли **db** и **app** в шаблонах **packer** - **app.json и db.json**:
Ты их только в ридми используешь?
Плейбуки как-то не сильно поменялись

2018-01-31 10:53 UTC, Nklya commented on README.md
> +      "ansible_env_vars": ["ANSIBLE_ROLES_PATH={{ user `ansible_path` }}/ansible/roles"],
Следов этого тоже не замечено в шаблонах

2018-01-31 11:04 UTC, Nklya commented
Я тут посмотрел твою роль https://github.com/rastamalik/test-ansible-role-with-travis.
Ты закоммитил туда приватные ssh ключи, и что гораздо хуже - ключи доступа к GCP. Тебе нужно как можно быстрее удалить слитый ключ этого сервисного пользователя

Слитые ключи находят довольно быстро - возможно на твоей учетке уже идет активно какой-нибудь майнинг.

А потом уже разобраться, как ты умудрился залить их сюда.

2018-01-31 11:55 UTC, rastamalik commented
Удалил, по запарке засунул. Все параллельно работе делается, поэтому где то
могу не доглядеть, а с гитом сам не понимаю откуда мусор лезет, все ветки
делаю от мастера и т.д.

31 января 2018 г., 14:04 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> Я тут посмотрел твою роль https://github.com/rastamalik/
> test-ansible-role-with-travis.
> Ты закоммитил туда приватные ssh ключи, и что гораздо хуже - ключи доступа
> к GCP. Тебе нужно как можно быстрее удалить слитый ключ этого сервисного
> пользователя
>
> Слитые ключи находят довольно быстро - возможно на твоей учетке уже идет
> активно какой-нибудь майнинг.
>
> А потом уже разобраться, как ты умудрился залить их сюда.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/12#issuecomment-361899062>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsB8rPL6fpdixGSFI-Miy00cC-Tnpks5tQEimgaJpZM4RwPYR>
> .
>

2018-01-31 11:58 UTC, Nklya commented
1. Нужно не просто удалить, а деактивировать сам ключ в GCP
2. А попали они в репозиторий потому что у тебя не было .gitignore
3. А не было его потому что ты не смотришь, что ты коммитишь.

2018-02-02 13:45 UTC, closed without merging