Homework-13
Otus-DevOps-2017-11/rastamalik_infra pull request #15
Opened 2018-02-03 16:42 UTC by rastamalik

Выполнил ДЗ-13

2018-02-05 18:36 UTC, Nklya requested changes
Добрый вечер.

Зачем каждый раз удалять PR, если можно фиксить его коммитами в ветку?

1. Закоммичены *.pyc и *.log файлы от молекулы. Их нужно вычистить
2. Я не вижу шаблонов пакера packer/app.json и packer/db.json. Их нужно сделать.
3. В плейбуках app.yml, db.yml до сих  пор указаны vars:, хотя они не используютя. Их нужно удалить.

ЭТОТ PR УДАЛЯТЬ НЕ НУЖНО!
ФИКСЫ КОМИТЯТСЯ В ВЕТКУ **ansible-4**

2018-02-06 07:53 UTC, rastamalik commented
Поправил

5 февраля 2018 г., 21:36 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
> Добрый вечер.
>
> Зачем каждый раз удалять PR, если можно фиксить его коммитами в ветку?
>
>    1. Закоммичены *.pyc и *.log файлы от молекулы. Их нужно вычистить
>    2. Я не вижу шаблонов пакера packer/app.json и packer/db.json. Их
>    нужно сделать.
>    3. В плейбуках app.yml, db.yml до сих пор указаны vars:, хотя они не
>    используютя. Их нужно удалить.
>
> ЭТОТ PR УДАЛЯТЬ НЕ НУЖНО!
> ФИКСЫ КОМИТЯТСЯ В ВЕТКУ ansible-4
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/15#pullrequestreview-94095681>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsIGOm3jaTXYY8TQ2QYPqbbwm44Jsks5tR0pAgaJpZM4R4Oz3>
> .
>

2018-02-06 09:42 UTC, Nklya approved these changes
Да, сейчас относительно нормально.

Замечания:
1. Так и не вычистил `ansible/roles/db/molecule/default/tests/__pycache__/test_default.cpython-27-PYTEST.pyc`
Можно же открыть список изменений https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/15/files и посмореть все ли нормально закоммичено?
2. Путь к ролям в пакере указывается странно

2018-02-06 09:42 UTC, Nklya commented on packer/db.json
> +      "ansible_env_vars": ["ANSIBLE_ROLES_PATH={{user `role_path` }}/ansible/roles"],
Зачем указывать путь к ролям, если можно использовать относительные пути от пакера?
Пример дан в слайдах.

2018-02-06 10:53 UTC, merged