Homework 07
Otus-DevOps-2017-11/rastamalik_infra pull request #3
Opened 2017-12-25 07:04 UTC by rastamalik

Выполнил ДЗ 07

2017-12-25 15:50 UTC, vitkhab requested changes
Опиши, пожалуйста, в `readme` как запустить твой проект и как им пользоваться.
Также добавь в PR валидный файл `variables.json.example`

2017-12-27 10:12 UTC, vitkhab commented
`variables.json` - это файл с переменными, а не полноценный шаблон. В нем мы только задаем нужные нам значения. Подробнее https://www.packer.io/docs/templates/user-variables.html#from-a-file

Задача ДЗ научиться параметризировать шаблон, определять переменные через командную строку и файл `variables.json`.
Ясна ли задача? Понятно ли что нужно переделать? Есть ли какие-либо другие вопросы?

2017-12-27 11:13 UTC, rastamalik commented
Теперь понял, я не совсем сначала понимал "параметризировать созданный
шаблон", теперь понял.

27 декабря 2017 г., 13:12 пользователь Vitaly Khabarov <
notifications@github.com> написал:

> variables.json - это файл с переменными, а не полноценный шаблон. В нем
> мы только задаем нужные нам значения. Подробнее
> https://www.packer.io/docs/templates/user-variables.html#from-a-file
>
> Задача ДЗ научиться параметризировать шаблон, определять переменные через
> командную строку и файл variables.json.
> Ясна ли задача? Понятно ли что нужно переделать? Есть ли какие-либо другие
> вопросы?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/3#issuecomment-354090290>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsAkWJWepLOvz2puUl_HEkRXFx2zTks5tEhgcgaJpZM4RMJdU>
> .
>

2017-12-28 14:44 UTC, vitkhab requested changes
Молодец! Прогресс на лицо, хорошо поработал.

Для зачета прошу параметризировать `immutable.json`, также как и `ubuntu16.json`

Еще хорошей практикой является переиспользование. Можешь выделить из `files/deploy.sh` уникальную часть, а для установки mongo и ruby использовать те же скрипты, что и для `reddit-base`

2017-12-28 14:44 UTC, vitkhab commented on packer/ubuntu16.json
> +    "project_id1": "",
Можно так, а можно указывать `null` (без кавычек) вместо значения

2017-12-28 14:44 UTC, vitkhab commented on packer/immutable.json
> +"project_id": "clever-overview-188908",
Хорошо бы параметризировать, как и `ubuntu-16.json`

2018-01-09 14:17 UTC, vitkhab approved these changes
Молодец! Исправил все замечания. Проект получился годный, так держать!

2018-01-15 12:55 UTC, merged