HOMEWORK 09
Otus-DevOps-2017-11/rastamalik_infra pull request #5
Opened 2018-01-10 07:39 UTC by rastamalik

Выполнеено ДЗ 9

2018-01-13 21:09 UTC, Nklya requested changes
Добрый вечер.

Александр, есть кучка проблем.
1. Почему закоммичена .terraform?
2. Почему закоммичена terraform2? Она нужна была только для эксперимента
3. Почему закоммичены tfstate?
4. Форматирование в ридми кривое. Хотя бы блоки выдели в ```

В общем и в целом,  когда делаешь PR смотри на дифф, сразу же видно, что дичь получается.

Вычисти весь мусор, потом повторное ревью.

2018-01-13 21:09 UTC, Nklya commented on terraform2/.gitignore
> +ignore.txt
Зачем коммитить terraform2?

2018-01-13 21:09 UTC, Nklya commented on terraform/terraform.tfstate
> +{
Почему tfstate закомичен?

2018-01-13 21:09 UTC, Nklya commented on terraform/main.tf.save.1
> +provider "google" {
Это здесь зачем?

2018-01-13 21:09 UTC, Nklya commented on terraform/.gitignore
> +ignore.txt
Зачем отдельный .gitignore, есть есть в корне?

2018-01-15 07:31 UTC, rastamalik commented
Николай привет, я может не понял, 9-ДЗ выполнять в той же папке terraform,
terraform2 не создавать?

14 января 2018 г., 0:09 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
> Добрый вечер.
>
> Александр, есть кучка проблем.
>
>    1. Почему закоммичена .terraform?
>    2. Почему закоммичена terraform2? Она нужна была только для
>    эксперимента
>    3. Почему закоммичены tfstate?
>    4. Форматирование в ридми кривое. Хотя бы блоки выдели в ```
>
> В общем и в целом, когда делаешь PR смотри на дифф, сразу же видно, что
> дичь получается.
>
> Вычисти весь мусор, потом повторное ревью.
> ------------------------------
>
> In terraform2/.gitignore
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#discussion_r161381582>
> :
>
> > @@ -0,0 +1 @@
> +ignore.txt
>
> Зачем коммитить terraform2?
> ------------------------------
>
> In terraform/terraform.tfstate
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#discussion_r161381591>
> :
>
> > @@ -0,0 +1,16 @@
> +{
>
> Почему tfstate закомичен?
> ------------------------------
>
> In terraform/main.tf.save.1
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#discussion_r161381598>
> :
>
> > @@ -0,0 +1,130 @@
> +provider "google" {
>
> Это здесь зачем?
> ------------------------------
>
> In terraform/.gitignore
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#discussion_r161381606>
> :
>
> > @@ -0,0 +1 @@
> +ignore.txt
>
> Зачем отдельный .gitignore, есть есть в корне?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#pullrequestreview-88667352>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsCStN76d4mmBBmNoMRKpIkmszEkvks5tKRt4gaJpZM4RY61b>
> .
>

2018-01-15 08:20 UTC, Nklya commented
Привет. 
Да, 9 дз в той же папке. Это развитие предыдущего дз.

2018-01-15 08:21 UTC, rastamalik commented
Понял, спасибо, сейчас все поправлю.

2018-01-15 11:20 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> Привет.
> Да, 9 дз в той же папке. Это развитие предыдущего дз.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#issuecomment-357611318>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsKL9J0r3cbJ5dqCv78PxKz3iZ8sSks5tKwoygaJpZM4RY61b>
> .
>

2018-01-15 10:23 UTC, Nklya commented
Зачем ты делаешь так много коммитов для одного файла?

2018-01-15 11:00 UTC, rastamalik commented
Да я форматирование пробовал смотрел, не подумал что он коммитится

2018-01-15 13:23 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> Зачем ты делаешь так много коммитов для одного файла?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#issuecomment-357641256>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsHnWEp9s61lq768WeO6S9UK3hPD4ks5tKycLgaJpZM4RY61b>
> .
>

2018-01-15 11:17 UTC, rastamalik commented
Поправил ДЗ

2018-01-15 13:23 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> Зачем ты делаешь так много коммитов для одного файла?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#issuecomment-357641256>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsHnWEp9s61lq768WeO6S9UK3hPD4ks5tKycLgaJpZM4RY61b>
> .
>

2018-01-15 11:40 UTC, Nklya requested changes
1. Почему в этой ветке нет результатов предыдущих ДЗ?
2. Почему .gitignore находится в terraform. Вынеси его в корень
3. Почему закоммичены prod2, stage2, app.tf.example, db.tf.example, terraform.tfstate с бекапом, директория .terraform.

В общем, сделай так чтобы в этой ветке были все результаты предыдущих ДЗ, вычисти репозиторий от мусора из пункта 3. И пофикси пункт 2.

2018-01-15 13:02 UTC, rastamalik commented
Поправил, проверь.

15 января 2018 г., 14:40 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
>    1. Почему в этой ветке нет результатов предыдущих ДЗ?
>    2. Почему .gitignore находится в terraform. Вынеси его в корень
>    3. Почему закоммичены prod2, stage2, app.tf.example, db.tf.example,
>    terraform.tfstate с бекапом, директория .terraform.
>
> В общем, сделай так чтобы в этой ветке были все результаты предыдущих ДЗ,
> вычисти репозиторий от мусора из пункта 3. И пофикси пункт 2.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#pullrequestreview-88792681>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsGtD9AuN9VUzo9cwiuNPVzxJSQXQks5tKzklgaJpZM4RY61b>
> .
>

2018-01-15 13:14 UTC, Nklya requested changes
1. Все предыдущие PR, на которых стоит approved, должны быть смержены в мастер.
2. terraform.tfvars нужно удалить
3. В variables.tf остался какой-то мусор от мержа
4. Файлы main.tf, outputs.tf в папке terraform не нужны, сейчас все окружения в stage и prod.
5. В terraform/variables.tf лишние переменные
6. Куда делся .gitignore?

2018-01-15 13:34 UTC, rastamalik commented
Поправил, так вроде все ветки смержены.

15 января 2018 г., 16:14 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
>    1. Все предыдущие PR, на которых стоит approved, должны быть смержены
>    в мастер.
>    2. terraform.tfvars нужно удалить
>    3. В variables.tf остался какой-то мусор от мержа
>    4. Файлы main.tf, outputs.tf в папке terraform не нужны, сейчас все
>    окружения в stage и prod.
>    5. В terraform/variables.tf лишние переменные
>    6. Куда делся .gitignore?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#pullrequestreview-88814834>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsOZu15eIdlH53kojPoANSf6zrOLYks5tK08igaJpZM4RY61b>
> .
>

2018-01-15 13:43 UTC, Nklya commented
1. Не смержены. Смержены, это когда фиолетовые значки будут.
<img width="448" alt="screen shot 2018-01-15 at 16 38 27" src="https://user-images.githubusercontent.com/26086394/34945077-0d670f3a-fa13-11e7-9f4d-e7d5a73b3f65.png">
2. Как по-твоему будет работать `storage-bucket.tf`, если нет variables.tf?
3. .gitignore где?

2018-01-15 16:05 UTC, rastamalik commented
Смержил ветки, variables.tf вернул( выпал при push), а .gitignore у меня в
корне ветки master, или я опять не туда поместил?

15 января 2018 г., 16:43 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

>
>    1. Не смержены. Смержены, это когда фиолетовые значки будут.
>
> [image: screen shot 2018-01-15 at 16 38 27]
> <https://user-images.githubusercontent.com/26086394/34945077-0d670f3a-fa13-11e7-9f4d-e7d5a73b3f65.png>
> 2. Как по-твоему будет работать `storage-bucket.tf`, если нет variables.tf?
> 3. .gitignore где?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#issuecomment-357686518>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsIQ7dQyvY1BcVYlPWnPz3mm9YFiDks5tK1YZgaJpZM4RY61b>
> .
>

2018-01-15 16:14 UTC, Nklya commented
Лишние в корне deploy.sh, install_mongodb.sh, install_ruby.sh, run_app.sh.
.gitignore должен быть в корне репозитория в этой ветке.
В terraform/variables.tf лишние переменные

2018-01-15 16:41 UTC, rastamalik commented
Поправил.

2018-01-15 19:14 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> Лишние в корне deploy.sh, install_mongodb.sh, install_ruby.sh, run_app.sh.
> .gitignore должен быть в корне репозитория в этой ветке.
> В terraform/variables.tf лишние переменные
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/5#issuecomment-357727042>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsLQSzbOQmK9rqX3cQFiw9VL0JLBbks5tK3legaJpZM4RY61b>
> .
>

2018-01-15 16:49 UTC, Nklya approved these changes
Да, теперь все относительно ок.

Замечания ниже, аппрув ставлю сейчас.

2018-01-15 16:49 UTC, Nklya commented on terraform/variables.tf
> +default = "clever-overview-188908"
Не особо хорошо сюда хардкодить имя проекта.

2018-01-15 16:49 UTC, Nklya commented on terraform/variables.tf
>  variable app_disk_image {
Эти переменные здесь не нужны, в корне папки терраформ нет поднятия инстансов.

2018-01-15 16:49 UTC, Nklya commented on terraform/variables.tf
>  variable db_disk_image {
Эти переменные здесь не нужны, в корне папки терраформ нет поднятия инстансов.

2018-01-15 16:49 UTC, Nklya commented on terraform/storage-bucket.tf
> +name = ["storage-bucket-test5", "storage-bucket-test6"]
В чем смысл поменять здесь цифры?

2018-01-15 16:49 UTC, Nklya commented on config-scripts/install_ruby.sh
> +<<<<<<< HEAD
Это остатки от резолва конфликтов. Зачем они здесь?

2018-01-15 16:49 UTC, Nklya commented on README.md
> +<<<<<<< HEAD
Это остатки от резолва конфликтов. Зачем они здесь?

2018-01-15 16:49 UTC, Nklya commented on README.md
> +>>>>>>> Infra-2
Это остатки от резолва конфликтов. Зачем они здесь?

2018-01-16 05:48 UTC, merged