Homework 10
Otus-DevOps-2017-11/rastamalik_infra pull request #6
Opened 2018-01-12 08:29 UTC by rastamalik

Выполнил ДЗ 10

2018-01-16 19:24 UTC, Nklya requested changes
Label должен называться homework-10, т.е. там должен быть дефис.

2018-01-17 06:09 UTC, rastamalik commented
Поправил

2018-01-16 22:24 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> *@Nklya* requested changes on this pull request.
>
> Label должен называться homework-10, т.е. там должен быть дефис.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/6#pullrequestreview-89218131>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsOVLmH5y7BbtOYhBNTxUl9xKhtUvks5tLPdhgaJpZM4Rb9eI>
> .
>

2018-01-22 14:54 UTC, Nklya requested changes
Добрый вечер.

Александр, все выглядит относительно нормально.

Нужно: вернуть в README.md все, что было написано в предыдущих PR.
С чего вдруг ты их чистишь на каждое дз?

P.S. Конструкция `ansible all -m ping -i  inventory.json` работать не будет.

2018-01-23 06:25 UTC, rastamalik commented
Поправил, а насчет ansible all -m ping -i inventory.json, только что
проверял только с другими IP, все работает.

22 января 2018 г., 17:54 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
> Добрый вечер.
>
> Александр, все выглядит относительно нормально.
>
> Нужно: вернуть в README.md все, что было написано в предыдущих PR.
> С чего вдруг ты их чистишь на каждое дз?
>
> P.S. Конструкция ansible all -m ping -i inventory.json работать не будет.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/6#pullrequestreview-90497443>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsNcnGE776igBILd4c_v920INcHFwks5tNKESgaJpZM4Rb9eI>
> .
>

2018-01-23 06:38 UTC, Nklya commented
В задании я добавил уточнение, что json инвентори нужно было рассмотреть такое, чтобы оно работало с ansible начиная с 2.0 верссии

2018-01-23 06:41 UTC, Nklya approved these changes
Да, теперь ок.

2018-01-23 06:43 UTC, merged