Homework-12
Otus-DevOps-2017-11/rastamalik_infra pull request #8
Opened 2018-01-25 11:30 UTC by rastamalik

Выполнено ДЗ-12

2018-01-25 21:10 UTC, Nklya requested changes
Сделай мерж мастера в эту ветку и пофикси конфликты. 

Сейчас в этом PR много лишних изменений.

2018-01-26 06:08 UTC, rastamalik commented
Поправил

2018-01-26 0:10 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> *@Nklya* requested changes on this pull request.
>
> Сделай мерж мастера в эту ветку и пофикси конфликты.
>
> Сейчас в этом PR много лишних изменений.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/8#pullrequestreview-91672109>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsFRJ2gJbyUyqdbReCSX6HbW1WQ94ks5tOO2ugaJpZM4Rstd8>
> .
>

2018-01-26 09:10 UTC, Nklya requested changes
И ты сам смотрел, что в итоге получилось?

Смысл мержа мастера в эту ветку был в том, чтобы убрать из диффа какие-то изменения в терраформе, которые уже были в мастере. 
Ты же вкомитил еще больше мусора, в том числе какие-то приватные ключи.

В общем, нужно привести дифф этого PR к тому состоянию, чтобы в нем были только изменения, сделанные в рамках 12 дз.

2018-01-26 12:36 UTC, merged

2018-01-26 13:26 UTC, rastamalik commented
Пересоздал ветку, сделал новый PR

26 января 2018 г., 12:10 пользователь Nikolay Antsiferov <
notifications@github.com> написал:

> *@Nklya* requested changes on this pull request.
>
> И ты сам смотрел, что в итоге получилось?
>
> Смысл мержа мастера в эту ветку был в том, чтобы убрать из диффа какие-то
> изменения в терраформе, которые уже были в мастере.
> Ты же вкомитил еще больше мусора, в том числе какие-то приватные ключи.
>
> В общем, нужно привести дифф этого PR к тому состоянию, чтобы в нем были
> только изменения, сделанные в рамках 12 дз.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/8#pullrequestreview-91777770>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsFH7kKtG5XrJRuCcHGjnS42p-9Gqks5tOZZxgaJpZM4Rstd8>
> .
>

2018-01-26 13:29 UTC, Nklya commented
И зачем?

2018-01-26 13:30 UTC, rastamalik commented
Не знал как все поправить, решил ветку пересоздать

2018-01-26 16:29 GMT+03:00 Nikolay Antsiferov <notifications@github.com>:

> И зачем?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/Otus-DevOps-2017-11/rastamalik_infra/pull/8#issuecomment-360784682>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AgvcsEwrHC5FEjw4fPcy1Hxwz3Bmlq7Qks5tOdNIgaJpZM4Rstd8>
> .
>